// Query-plan catalogue v1 (LLD §3.3; covers PRD Appendix A). The model may only choose a plan from here; the
// validator checks every field, operator and value against it and the adapter compiles it over this column allow-list.
import type { FieldSpec, GroupSpec, Op, OutputColumn, PlanTemplateDef } from './types.js';

export const CATALOGUE_VERSION = 'v1';

// ------------------------------------------------------------------------------------------ controlled values
export const OFFER_COMMERCIAL_STATUSES = [
  'Upcoming',
  'Available',
  'Matched',
  'In proposal',
  'Site visit',
  'In process',
  'Closed',
  'Inactive',
] as const;
/** "Active" / "available" offers in questions and the supply side of the gap: not closed, not inactive. */
export const ACTIVE_OFFER_STATUSES = ['Upcoming', 'Available', 'Matched', 'In proposal', 'Site visit', 'In process'];
export const DEMAND_STATUSES = [
  'New',
  'Contacted',
  'Active',
  'Sourcing',
  'Matched',
  'Proposal shared',
  'Site visit',
  'In process',
  'Closed',
] as const;
export const LIFE_STAGES = ['Fresh', 'Ageing', 'Stale', 'Expired', 'Paused'] as const;
export const RECORD_STAGES = ['Captured', 'Enriched', 'Contacted', 'Verified', 'Qualified'] as const;
export const PUBLICATION_LEVELS = ['Private', 'Anonymous', 'Public'] as const;
export const SOURCE_TYPES = ['Channel', 'Digi', 'Direct'] as const;
export const MATCH_STATUSES = ['Suggested', 'Confirmed', 'Rejected', 'Closed'] as const;
export const DEAL_STATUSES = ['open', 'closed', 'cancelled'] as const;
export const EXIT_TYPES = ['Lost', 'Dormant', 'Invalid'] as const;
export const FACT_METRICS = [
  'offer_created',
  'offer_verified',
  'offer_published_public',
  'demand_created',
  'demand_qualified',
  'demand_exit_lost',
  'demand_exit_dormant',
  'demand_exit_invalid',
  'match_suggested',
  'match_confirmed',
  'deal_opened',
  'deal_closed',
  'records_merged',
  'upload_rows_accepted',
  'upload_rows_rejected',
  'watchlist_created',
  'calls_logged',
] as const;

const BUSINESS_ROLES = ['Admin', 'Manager', 'Demand agent', 'Supply agent'] as const;
const ALL_ROLES = [...BUSINESS_ROLES, 'Data operator'] as const;

const SET: readonly Op[] = ['eq', 'in'];
const SET_NULL: readonly Op[] = ['eq', 'in', 'is_null', 'not_null'];
const NUM: readonly Op[] = ['eq', 'gte', 'lte', 'between'];
const RANGE: readonly Op[] = ['gte', 'lte', 'between'];
const DATE: readonly Op[] = ['gte', 'lte', 'between', 'is_null', 'not_null'];

// ------------------------------------------------------------------------------------------ field builders
const vocab = (field: string, label: string, column: string, vocabulary = field): FieldSpec => ({
  field,
  label,
  shape: 'scalar',
  type: 'text',
  ops: SET_NULL,
  vocabulary,
  column,
});
const vocabArray = (field: string, label: string, column: string, vocabulary: string): FieldSpec => ({
  field,
  label,
  shape: 'array',
  type: 'text',
  ops: SET,
  vocabulary,
  column,
});
const enumField = (field: string, label: string, column: string, values: readonly string[]): FieldSpec => ({
  field,
  label,
  shape: 'scalar',
  type: 'text',
  ops: SET_NULL,
  values,
  column,
});
const range = (field: string, label: string, min: string, max: string, type: 'number' | 'inr' = 'number'): FieldSpec => ({
  field,
  label,
  shape: 'range',
  type,
  ops: field === 'bhk' || field.endsWith('area_sqft') ? NUM : RANGE,
  min,
  max,
});
const dateField = (field: string, label: string, column: string, type: 'date' | 'datetime'): FieldSpec => ({
  field,
  label,
  shape: 'scalar',
  type,
  ops: DATE,
  column,
});
const scalar = (field: string, label: string, column: string, type: FieldSpec['type'], ops: readonly Op[]): FieldSpec => ({
  field,
  label,
  shape: 'scalar',
  type,
  ops,
  column,
});
const group = (key: string, label: string, column: string, type: GroupSpec['type'] = 'string'): GroupSpec => ({
  key,
  label,
  column,
  type,
});

// ------------------------------------------------------------------------------------------ offers
const OFFER_FILTERS: readonly FieldSpec[] = [
  scalar('code', 'Code', 'b.code', 'code', ['eq', 'in']),
  vocab('deal_type', 'Deal type', 'b.deal_type'),
  vocab('market', 'Market', 'b.market'),
  vocab('segment', 'Segment', 'b.segment'),
  vocabArray('property_type', 'Property type', 'b.property_types', 'property_type'),
  range('bhk', 'BHK', 'b.bhk_min', 'b.bhk_max'),
  range('area_sqft', 'Area (sq ft)', 'b.area_sqft_min', 'b.area_sqft_max'),
  range('sale_price_inr', 'Sale price', 'b.sale_price_inr_min', 'b.sale_price_inr_max', 'inr'),
  range('rent_monthly_inr', 'Monthly rent', 'b.rent_monthly_inr_min', 'b.rent_monthly_inr_max', 'inr'),
  { field: 'location', label: 'Location', shape: 'location', type: 'text', ops: SET, column: 'b.micromarket', localityColumn: 'b.locality' },
  enumField('commercial_status', 'Commercial status', 'b.commercial_status', OFFER_COMMERCIAL_STATUSES),
  enumField('life_stage', 'Life stage', 'b.life_stage', LIFE_STAGES),
  enumField('record_stage', 'Record stage', 'b.record_stage', RECORD_STAGES),
  enumField('publication_level', 'Publication', 'b.publication_level', PUBLICATION_LEVELS),
  enumField('source_type', 'Source type', 'b.source_type', SOURCE_TYPES),
  vocab('sale_mode', 'Sale mode', 'b.sale_mode'),
  vocab('tenancy_status', 'Tenancy', 'b.tenancy_status'),
  vocab('furnishing', 'Furnishing', 'b.furnishing'),
  vocab('possession_status', 'Possession', 'b.possession_status'),
  scalar('owner_user_id', 'Owner', 'b.owner_user_id', 'user', ['eq', 'in']),
  scalar('verified_by', 'Verified by', 'b.verified_by', 'user', ['eq', 'in']),
  scalar('outside_launch_area', 'Outside launch area', 'b.outside_launch_area', 'boolean', ['eq']),
  scalar('has_real_photos', 'Has real photos', 'b.has_real_photos', 'boolean', ['eq']),
  dateField('available_from', 'Available from', 'b.possession_sort', 'date'),
  dateField('verified_at', 'Verified at', 'b.verified_at', 'datetime'),
  dateField('life_stage_since', 'Life stage since', 'b.life_stage_since', 'datetime'),
  dateField('created_at', 'Added', 'b.created_at_src', 'datetime'),
];
const OFFER_GROUPS: readonly GroupSpec[] = [
  group('micromarket', 'Micromarket', 'b.micromarket'),
  group('locality', 'Locality', 'b.locality'),
  group('segment', 'Segment', 'b.segment'),
  group('deal_type', 'Deal type', 'b.deal_type'),
  group('market', 'Market', 'b.market'),
  group('property_type', 'Property type', 'b.property_type_primary'),
  group('commercial_status', 'Commercial status', 'b.commercial_status'),
  group('life_stage', 'Life stage', 'b.life_stage'),
  group('record_stage', 'Record stage', 'b.record_stage'),
  group('publication_level', 'Publication', 'b.publication_level'),
  group('source_type', 'Source type', 'b.source_type'),
  group('owner_user_id', 'Owner', 'b.owner_user_id', 'user'),
  group('verified_by', 'Verified by', 'b.verified_by', 'user'),
];
const OFFER_METRIC_COLUMNS = {
  sale_price_inr: 'b.sale_price_inr_min',
  rent_monthly_inr: 'b.rent_monthly_inr_min',
  area_sqft: 'b.area_sqft_min',
};
const OFFER_SORT_COLUMNS = {
  created_at: 'b.created_at_src',
  sale_price_inr: 'b.sale_price_inr_min',
  rent_monthly_inr: 'b.rent_monthly_inr_min',
  area_sqft: 'b.area_sqft_min',
  available_from: 'b.possession_sort',
  life_stage_since: 'b.life_stage_since',
  verified_at: 'b.verified_at',
};
const OFFER_PERIODS = [
  { field: 'created_at', column: 'b.created_at_src', type: 'datetime' as const },
  { field: 'life_stage_since', column: 'b.life_stage_since', type: 'datetime' as const },
  { field: 'verified_at', column: 'b.verified_at', type: 'datetime' as const },
  { field: 'available_from', column: 'b.possession_sort', type: 'date' as const },
];
export const OFFER_COLUMNS: readonly OutputColumn[] = [
  { key: 'code', label: 'Code', type: 'code', column: 'b.code' },
  { key: 'label', label: 'For', type: 'label' },
  { key: 'property_type', label: 'Property type', type: 'string', column: 'b.property_type_primary' },
  { key: 'bhk', label: 'BHK', type: 'number', column: 'b.bhk_min' },
  { key: 'area_sqft', label: 'Area (sq ft)', type: 'number', column: 'b.area_sqft_min' },
  { key: 'sale_price_inr', label: 'Price', type: 'inr', column: 'b.sale_price_inr_min' },
  { key: 'rent_monthly_inr', label: 'Rent / month', type: 'inr', column: 'b.rent_monthly_inr_min' },
  { key: 'locality', label: 'Locality', type: 'string', column: 'b.locality' },
  { key: 'micromarket', label: 'Micromarket', type: 'string', column: 'b.micromarket' },
  { key: 'commercial_status', label: 'Status', type: 'string', column: 'b.commercial_status' },
  { key: 'life_stage', label: 'Life stage', type: 'string', column: 'b.life_stage' },
  { key: 'record_stage', label: 'Record stage', type: 'string', column: 'b.record_stage' },
  { key: 'publication_level', label: 'Publication', type: 'string', column: 'b.publication_level' },
  { key: 'available_from', label: 'Available from', type: 'date', column: 'b.possession_sort' },
  { key: 'owner_user_id', label: 'Owner', type: 'user', column: 'b.owner_user_id' },
  { key: 'created_at', label: 'Added', type: 'datetime', column: 'b.created_at_src' },
];
/** Hidden columns the label generator needs. */
export const OFFER_LABEL_INPUTS = { dealType: 'b.deal_type', market: 'b.market', segment: 'b.segment' };

// ------------------------------------------------------------------------------------------ demands
const DEMAND_FILTERS: readonly FieldSpec[] = [
  scalar('code', 'Code', 'b.code', 'code', ['eq', 'in']),
  vocabArray('deal_type', 'Deal type', 'b.deal_types', 'deal_type'),
  vocab('market', 'Market', 'b.market'),
  vocab('segment', 'Segment', 'b.segment'),
  vocabArray('property_type', 'Property type', 'b.property_types', 'property_type'),
  range('bhk', 'BHK', 'b.bhk_min', 'b.bhk_max'),
  range('area_sqft', 'Area (sq ft)', 'b.area_sqft_min', 'b.area_sqft_max'),
  range('budget_inr', 'Budget', 'b.budget_inr_min', 'b.budget_inr_max', 'inr'),
  range('rent_monthly_inr', 'Monthly rent', 'b.rent_monthly_inr_min', 'b.rent_monthly_inr_max', 'inr'),
  { field: 'location', label: 'Location', shape: 'location', type: 'text', ops: SET, column: 'b.micromarkets', localityColumn: 'b.localities', arrays: true },
  enumField('commercial_status', 'Status', 'b.commercial_status', DEMAND_STATUSES),
  enumField('life_stage', 'Life stage', 'b.life_stage', LIFE_STAGES),
  enumField('record_stage', 'Record stage', 'b.record_stage', RECORD_STAGES),
  enumField('source_type', 'Source type (first touch)', 'b.source_type', SOURCE_TYPES),
  enumField('exit_type', 'Exit', 'b.exit_type', EXIT_TYPES),
  scalar('owner_user_id', 'Owner', 'b.owner_user_id', 'user', ['eq', 'in']),
  { field: 'days_in_sourcing', label: 'Days in Sourcing', shape: 'days_since', type: 'number', ops: ['gte', 'lte'], column: 'b.sourcing_since' },
  dateField('qualified_at', 'Qualified', 'b.qualified_at', 'datetime'),
  dateField('move_in_by', 'Move in by', 'b.move_in_by', 'date'),
  dateField('created_at', 'Added', 'b.created_at_src', 'datetime'),
];
const DEMAND_GROUPS: readonly GroupSpec[] = [
  group('micromarket', 'Micromarket', 'b.micromarkets[1]'),
  group('segment', 'Segment', 'b.segment'),
  group('deal_type', 'Deal type', 'b.deal_type_primary'),
  group('market', 'Market', 'b.market'),
  group('property_type', 'Property type', 'b.property_type_primary'),
  group('commercial_status', 'Status', 'b.commercial_status'),
  group('life_stage', 'Life stage', 'b.life_stage'),
  group('record_stage', 'Record stage', 'b.record_stage'),
  group('source_type', 'Source type', 'b.source_type'),
  group('exit_type', 'Exit', 'b.exit_type'),
  group('owner_user_id', 'Owner', 'b.owner_user_id', 'user'),
];
const DEMAND_PERIODS = [
  { field: 'created_at', column: 'b.created_at_src', type: 'datetime' as const },
  { field: 'qualified_at', column: 'b.qualified_at', type: 'datetime' as const },
  { field: 'sourcing_since', column: 'b.sourcing_since', type: 'datetime' as const },
];
export const DEMAND_COLUMNS: readonly OutputColumn[] = [
  { key: 'code', label: 'Code', type: 'code', column: 'b.code' },
  { key: 'label', label: 'Wants', type: 'label' },
  { key: 'property_type', label: 'Property type', type: 'string', column: 'b.property_type_primary' },
  { key: 'bhk', label: 'BHK', type: 'number', column: 'b.bhk_min' },
  { key: 'area_sqft', label: 'Area (sq ft)', type: 'number', column: 'b.area_sqft_max' },
  { key: 'budget_inr', label: 'Budget', type: 'inr', column: 'b.budget_inr_max' },
  { key: 'rent_monthly_inr', label: 'Rent / month', type: 'inr', column: 'b.rent_monthly_inr_max' },
  { key: 'micromarket', label: 'Micromarket', type: 'string', column: 'b.micromarkets[1]' },
  { key: 'commercial_status', label: 'Status', type: 'string', column: 'b.commercial_status' },
  { key: 'life_stage', label: 'Life stage', type: 'string', column: 'b.life_stage' },
  { key: 'source_type', label: 'Source', type: 'string', column: 'b.source_type' },
  { key: 'sourcing_since', label: 'In Sourcing since', type: 'datetime', column: 'b.sourcing_since' },
  { key: 'owner_user_id', label: 'Owner', type: 'user', column: 'b.owner_user_id' },
  { key: 'created_at', label: 'Added', type: 'datetime', column: 'b.created_at_src' },
];
export const DEMAND_LABEL_INPUTS = { dealType: 'b.deal_type_primary', market: 'b.market', segment: 'b.segment' };

// ------------------------------------------------------------------------------------------ matches, deals, prices
const MATCH_FILTERS: readonly FieldSpec[] = [
  enumField('status', 'Match status', 'b.status', MATCH_STATUSES),
  scalar('demand_code', 'Demand', 'd.code', 'code', ['eq', 'in']),
  vocab('demand_segment', 'Demand segment', 'd.segment', 'segment'),
  vocabArray('demand_deal_type', 'Demand deal type', 'd.deal_types', 'deal_type'),
  vocabArray('demand_property_type', 'Demand property type', 'd.property_types', 'property_type'),
  range('demand_area_sqft', 'Demand area (sq ft)', 'd.area_sqft_min', 'd.area_sqft_max'),
  dateField('suggested_at', 'Suggested', 'b.suggested_at', 'datetime'),
];
const MATCH_COLUMNS: readonly OutputColumn[] = [
  { key: 'code', label: 'Match', type: 'code', column: 'b.code' },
  { key: 'demand_code', label: 'Demand', type: 'code', column: 'd.code' },
  { key: 'is_bundle', label: 'Bundle', type: 'boolean', column: 'b.is_bundle' },
  { key: 'offer_count', label: 'Offers', type: 'integer', column: 'cardinality(b.offer_ids)' },
  { key: 'status', label: 'Status', type: 'string', column: 'b.status' },
  { key: 'score', label: 'Score', type: 'number', column: 'b.score' },
  { key: 'demand_area_sqft', label: 'Demand area (sq ft)', type: 'number', column: 'd.area_sqft_max' },
  { key: 'suggested_at', label: 'Suggested', type: 'datetime', column: 'b.suggested_at' },
];

const DEAL_FILTERS: readonly FieldSpec[] = [
  enumField('status', 'Deal status', 'b.status', DEAL_STATUSES),
  scalar('stage', 'Stage', 'b.stage', 'text', ['eq', 'in']),
  dateField('follow_up_date', 'Follow-up date', 'b.follow_up_date', 'date'),
  scalar('overdue', 'Overdue', 'b.overdue', 'boolean', ['eq']),
  vocab('deal_type', 'Deal type', 'b.deal_type'),
  vocab('segment', 'Segment', 'b.segment'),
  { field: 'location', label: 'Location', shape: 'location', type: 'text', ops: SET, column: 'b.micromarket', localityColumn: 'b.locality' },
  scalar('owner_user_id', 'Owner', 'b.owner_user_id', 'user', ['eq', 'in']),
  dateField('opened_at', 'Opened', 'b.opened_at', 'datetime'),
  dateField('closed_at', 'Closed', 'b.closed_at', 'datetime'),
];
const DEAL_COLUMNS: readonly OutputColumn[] = [
  { key: 'code', label: 'Deal', type: 'code', column: 'b.code' },
  { key: 'stage', label: 'Stage', type: 'string', column: 'b.stage' },
  { key: 'status', label: 'Status', type: 'string', column: 'b.status' },
  { key: 'follow_up_date', label: 'Follow-up', type: 'date', column: 'b.follow_up_date' },
  { key: 'overdue', label: 'Overdue', type: 'boolean', column: 'b.overdue' },
  { key: 'deal_type', label: 'Deal type', type: 'string', column: 'b.deal_type' },
  { key: 'segment', label: 'Segment', type: 'string', column: 'b.segment' },
  { key: 'micromarket', label: 'Micromarket', type: 'string', column: 'b.micromarket' },
  { key: 'closing_price_inr', label: 'Closing price', type: 'inr', column: 'b.closing_price_inr' },
  { key: 'owner_user_id', label: 'Owner', type: 'user', column: 'b.owner_user_id' },
  { key: 'opened_at', label: 'Opened', type: 'datetime', column: 'b.opened_at' },
];

const PRICE_FILTERS: readonly FieldSpec[] = [
  vocab('deal_type', 'Deal type', 'b.deal_type'),
  vocab('segment', 'Segment', 'b.segment'),
  vocab('property_type', 'Property type', 'b.property_type_primary', 'property_type'),
  { field: 'location', label: 'Location', shape: 'location', type: 'text', ops: SET, column: 'b.micromarket', localityColumn: 'b.locality' },
  enumField('source', 'Price source', 'b.source', ['closed_by_us', 'retired_known', 'closed_elsewhere', 'reported']),
  range('area_sqft', 'Area (sq ft)', 'b.area_sqft', 'b.area_sqft'),
];

// ------------------------------------------------------------------------------------------ templates
const offerBase = {
  base: 'offer' as const,
  baseTable: 'rm_offer',
  filters: OFFER_FILTERS,
  groupBy: OFFER_GROUPS,
  metricColumns: OFFER_METRIC_COLUMNS,
  sortColumns: OFFER_SORT_COLUMNS,
  periodFields: OFFER_PERIODS,
  meColumn: 'b.owner_user_id',
  columns: OFFER_COLUMNS,
  roles: BUSINESS_ROLES,
};
const offerMetrics = ['count', ...['avg', 'median', 'min', 'max'].flatMap((f) => Object.keys(OFFER_METRIC_COLUMNS).map((c) => `${f}:${c}`))];

const demandBase = {
  base: 'demand' as const,
  baseTable: 'rm_demand',
  filters: DEMAND_FILTERS,
  groupBy: DEMAND_GROUPS,
  metricColumns: { budget_inr: 'b.budget_inr_max', rent_monthly_inr: 'b.rent_monthly_inr_max', area_sqft: 'b.area_sqft_max' },
  sortColumns: {
    created_at: 'b.created_at_src',
    sourcing_since: 'b.sourcing_since',
    qualified_at: 'b.qualified_at',
    budget_inr: 'b.budget_inr_max',
    area_sqft: 'b.area_sqft_max',
  },
  periodFields: DEMAND_PERIODS,
  meColumn: 'b.owner_user_id',
  columns: DEMAND_COLUMNS,
  roles: BUSINESS_ROLES,
};

export const CATALOGUE: readonly PlanTemplateDef[] = [
  {
    ...offerBase,
    planId: 'list_offers',
    version: 1,
    kind: 'list',
    description: 'List offers (supply) filtered by stored fields',
    groupBy: [],
    metrics: [],
    sort: Object.keys(OFFER_SORT_COLUMNS),
    defaultSort: { field: 'created_at', dir: 'desc' },
    maxRows: 100,
  },
  {
    ...offerBase,
    planId: 'count_offers',
    version: 1,
    kind: 'count',
    description: 'Count offers (supply) filtered by stored fields',
    groupBy: [],
    metrics: ['count'],
    sort: [],
    maxRows: 1,
  },
  {
    ...offerBase,
    planId: 'group_offers',
    version: 1,
    kind: 'group',
    description: 'Offers grouped by one or two stored fields, with counts or price/area statistics',
    metrics: offerMetrics,
    sort: [],
    defaultMetrics: [{ fn: 'count' }],
    maxRows: 100,
  },
  {
    ...demandBase,
    planId: 'list_demands',
    version: 1,
    kind: 'list',
    description: 'List demands (requirements) filtered by stored fields',
    groupBy: [],
    metrics: [],
    sort: ['created_at', 'sourcing_since', 'qualified_at', 'budget_inr', 'area_sqft'],
    defaultSort: { field: 'created_at', dir: 'desc' },
    maxRows: 100,
  },
  {
    ...demandBase,
    planId: 'count_demands',
    version: 1,
    kind: 'count',
    description: 'Count demands filtered by stored fields',
    groupBy: [],
    metrics: ['count'],
    sort: [],
    maxRows: 1,
  },
  {
    ...demandBase,
    planId: 'group_demands',
    version: 1,
    kind: 'group',
    description: 'Demands grouped by one or two stored fields',
    metrics: ['count', 'avg:budget_inr', 'median:budget_inr', 'avg:rent_monthly_inr', 'avg:area_sqft'],
    sort: [],
    defaultMetrics: [{ fn: 'count' }],
    maxRows: 100,
  },
  {
    planId: 'supply_demand_gap',
    version: 1,
    kind: 'group',
    description: 'Open demand vs matching available supply per micromarket (rollups); micromarkets where demand exceeds supply',
    base: 'gap',
    baseTable: 'rm_demand_rollup,rm_offer_rollup',
    filters: [
      vocab('deal_type', 'Deal type', 'deal_type'),
      vocab('segment', 'Segment', 'segment'),
      vocab('market', 'Market', 'market'),
      vocab('property_type', 'Property type', 'property_type_primary', 'property_type'),
    ],
    groupBy: [group('micromarket', 'Micromarket', 'micromarket')],
    defaultGroupBy: ['micromarket'],
    metrics: ['count'],
    sort: [],
    columns: [
      { key: 'micromarket', label: 'Micromarket', type: 'string' },
      { key: 'open_demand', label: 'Open demand', type: 'integer' },
      { key: 'supply', label: 'Matching supply', type: 'integer' },
      { key: 'gap', label: 'Gap', type: 'integer' },
    ],
    maxRows: 100,
    roles: BUSINESS_ROLES,
  },
  {
    planId: 'closed_price_stats',
    version: 1,
    kind: 'stats',
    description: 'Average, median, range and count of closed / known prices (our closes, known prices on retire, reported)',
    base: 'market_price',
    baseTable: 'rm_market_price',
    filters: PRICE_FILTERS,
    groupBy: [group('micromarket', 'Micromarket', 'b.micromarket'), group('property_type', 'Property type', 'b.property_type_primary')],
    metrics: ['count', ...['avg', 'median', 'min', 'max'].flatMap((f) => [`${f}:price_inr`, `${f}:rent_monthly_inr`])],
    metricColumns: { price_inr: 'b.price_inr', rent_monthly_inr: 'b.rent_monthly_inr' },
    sort: [],
    periodFields: [{ field: 'occurred_at', column: 'b.occurred_at', type: 'datetime' }],
    fixed: [],
    columns: [],
    maxRows: 100,
    roles: BUSINESS_ROLES,
  },
  {
    planId: 'list_matches',
    version: 1,
    kind: 'list',
    description: 'Matches (single offers and bundles) with their demand',
    base: 'match',
    baseTable: 'rm_match,rm_demand',
    filters: [...MATCH_FILTERS, scalar('is_bundle', 'Bundle', 'b.is_bundle', 'boolean', ['eq'])],
    groupBy: [],
    metrics: [],
    sort: ['suggested_at', 'score'],
    sortColumns: { suggested_at: 'b.suggested_at', score: 'b.score' },
    defaultSort: { field: 'suggested_at', dir: 'desc' },
    periodFields: [{ field: 'suggested_at', column: 'b.suggested_at', type: 'datetime' }],
    columns: MATCH_COLUMNS,
    maxRows: 100,
    roles: BUSINESS_ROLES,
  },
  {
    planId: 'list_bundles',
    version: 1,
    kind: 'list',
    description: 'Bundle matches (several offers together) with their demand',
    base: 'match',
    baseTable: 'rm_match,rm_demand',
    filters: MATCH_FILTERS,
    groupBy: [],
    metrics: [],
    sort: ['suggested_at', 'score'],
    sortColumns: { suggested_at: 'b.suggested_at', score: 'b.score' },
    defaultSort: { field: 'suggested_at', dir: 'desc' },
    periodFields: [{ field: 'suggested_at', column: 'b.suggested_at', type: 'datetime' }],
    fixed: [{ field: 'is_bundle', op: 'eq', value: true }],
    columns: MATCH_COLUMNS,
    maxRows: 100,
    roles: BUSINESS_ROLES,
  },
  {
    planId: 'list_deals',
    version: 1,
    kind: 'list',
    description: 'Deals (open, closed, cancelled) with stage and follow-up',
    base: 'deal',
    baseTable: 'rm_deal',
    filters: DEAL_FILTERS,
    groupBy: [],
    metrics: [],
    sort: ['follow_up_date', 'opened_at', 'closed_at'],
    sortColumns: { follow_up_date: 'b.follow_up_date', opened_at: 'b.opened_at', closed_at: 'b.closed_at' },
    defaultSort: { field: 'opened_at', dir: 'desc' },
    periodFields: [
      { field: 'opened_at', column: 'b.opened_at', type: 'datetime' },
      { field: 'closed_at', column: 'b.closed_at', type: 'datetime' },
      { field: 'follow_up_date', column: 'b.follow_up_date', type: 'date' },
    ],
    meColumn: 'b.owner_user_id',
    columns: DEAL_COLUMNS,
    maxRows: 100,
    roles: BUSINESS_ROLES,
  },
  {
    planId: 'list_my_followups',
    version: 1,
    kind: 'list',
    description: "The caller's open deals with a follow-up due (overdue first)",
    base: 'deal',
    baseTable: 'rm_deal',
    filters: DEAL_FILTERS.filter((f) => f.field !== 'owner_user_id' && f.field !== 'status'),
    groupBy: [],
    metrics: [],
    sort: ['follow_up_date'],
    sortColumns: { follow_up_date: 'b.follow_up_date' },
    defaultSort: { field: 'follow_up_date', dir: 'asc' },
    periodFields: [{ field: 'follow_up_date', column: 'b.follow_up_date', type: 'date' }],
    meColumn: 'b.owner_user_id',
    forceMe: true,
    fixed: [{ field: 'status', op: 'eq', value: 'open' }],
    columns: DEAL_COLUMNS,
    maxRows: 100,
    roles: BUSINESS_ROLES,
  },
  {
    planId: 'source_quality',
    version: 1,
    kind: 'group',
    description: 'Demand by first-touch source type (e.g. qualified demand per source)',
    base: 'demand',
    baseTable: 'rm_demand',
    filters: DEMAND_FILTERS.filter((f) => !['code', 'owner_user_id'].includes(f.field)),
    groupBy: [group('source_type', 'Source type', 'b.source_type')],
    defaultGroupBy: ['source_type'],
    metrics: ['count'],
    defaultMetrics: [{ fn: 'count' }],
    sort: [],
    periodFields: [
      { field: 'qualified_at', column: 'b.qualified_at', type: 'datetime' },
      { field: 'created_at', column: 'b.created_at_src', type: 'datetime' },
    ],
    columns: [],
    maxRows: 10,
    roles: BUSINESS_ROLES,
  },
  {
    planId: 'agent_activity',
    version: 1,
    kind: 'group',
    description: 'Daily activity facts per agent (e.g. offers verified, calls logged) over a period',
    base: 'daily_fact',
    baseTable: 'rm_daily_fact',
    filters: [
      enumField('metric', 'Activity', 'b.metric', FACT_METRICS),
      vocab('segment', 'Segment', 'b.segment'),
      vocab('deal_type', 'Deal type', 'b.deal_type'),
      enumField('source_type', 'Source type', 'b.source_type', SOURCE_TYPES),
      scalar('owner_user_id', 'Agent', 'b.owner_user_id', 'user', ['eq', 'in']),
    ],
    groupBy: [
      group('owner_user_id', 'Agent', 'b.owner_user_id', 'user'),
      group('day', 'Day', 'b.day', 'date'),
      group('metric', 'Activity', 'b.metric'),
      group('source_type', 'Source type', 'b.source_type'),
      group('segment', 'Segment', 'b.segment'),
    ],
    defaultGroupBy: ['owner_user_id'],
    metrics: ['sum:n'],
    metricColumns: { n: 'b.n' },
    defaultMetrics: [{ fn: 'sum', field: 'n' }],
    sort: [],
    periodFields: [{ field: 'day', column: 'b.day', type: 'date' }],
    meColumn: 'b.owner_user_id',
    columns: [],
    maxRows: 100,
    roles: BUSINESS_ROLES,
  },
  {
    planId: 'upload_quality',
    version: 1,
    kind: 'group',
    description: 'Uploads per source: rows accepted, rejected and needing review',
    base: 'upload',
    baseTable: 'rm_upload',
    filters: [
      scalar('source_type', 'Source', 'b.source_type', 'text', ['eq', 'in']),
      enumField('status', 'Upload status', 'b.status', ['running', 'completed', 'failed']),
      scalar('mode', 'Mode', 'b.mode', 'text', ['eq']),
    ],
    groupBy: [group('source_type', 'Source', 'b.source_type'), group('status', 'Upload status', 'b.status')],
    defaultGroupBy: ['source_type'],
    metrics: ['count', 'sum:accepted', 'sum:rejected', 'sum:needs_review', 'sum:row_count'],
    metricColumns: { accepted: 'b.accepted', rejected: 'b.rejected', needs_review: 'b.needs_review', row_count: 'b.row_count' },
    defaultMetrics: [{ fn: 'count' }, { fn: 'sum', field: 'accepted' }, { fn: 'sum', field: 'rejected' }],
    sort: [],
    periodFields: [{ field: 'started_at', column: 'b.started_at', type: 'datetime' }],
    columns: [],
    maxRows: 50,
    roles: ALL_ROLES,
  },
  {
    planId: 'open_my_queue',
    version: 1,
    kind: 'navigate',
    description: 'Open my queue (journeys GET /v1/queues/me)',
    base: 'none',
    baseTable: '-',
    filters: [],
    groupBy: [],
    metrics: [],
    sort: [],
    columns: [],
    maxRows: 0,
    roles: ALL_ROLES,
    navigate: { panel: 'P-01', targetService: 'journeys', targetOperation: 'getMyQueue' },
  },
  {
    planId: 'open_record',
    version: 1,
    kind: 'navigate',
    description: 'Open a record by display code (offer, demand, project, person)',
    base: 'none',
    baseTable: '-',
    filters: [scalar('code', 'Code', 'code', 'code', ['eq'])],
    groupBy: [],
    metrics: [],
    sort: [],
    columns: [],
    maxRows: 0,
    roles: ALL_ROLES,
    navigate: { panel: 'P-02', targetService: 'records', targetOperation: 'getOffer' },
  },
  {
    planId: 'export_list',
    version: 1,
    kind: 'export',
    description: 'Any list plan as an Excel file (the answer carries an exportable table; POST /v1/exports starts it)',
    base: 'none',
    baseTable: '-',
    filters: [],
    groupBy: [],
    metrics: [],
    sort: [],
    columns: [],
    maxRows: 0,
    roles: ALL_ROLES,
  },
];

export function templateOf(planId: string, version?: number): PlanTemplateDef | undefined {
  return CATALOGUE.find((t) => t.planId === planId && (version === undefined || t.version === version));
}

/** Data-plan templates the export and the Open-in-panel paths accept. */
export function isListTemplate(t: PlanTemplateDef): boolean {
  return t.kind === 'list';
}
