-- GENERATED by tools/gen-db-bootstrap.mjs from contracts/asyncapi/events.yaml + contracts/openapi. Do not edit.
-- Platform bootstrap (F-06): data-hosting §2–3, ADR-0003 (pgmq transport), ADR-0006 (schema + role per service).
-- Idempotent: roles are cluster-wide and survive `supabase db reset`, so every statement tolerates re-runs.
-- Passwords are never set here. Local: infra/scripts/local-roles.mjs. Pilot/production: provisioning runbook.

-- Extensions ----------------------------------------------------------------------------------------------
create extension if not exists pgmq;
create extension if not exists pg_cron;
create extension if not exists pg_net with schema extensions;

-- Hardening --------------------------------------------------------------------------------------------------
revoke create on schema public from public;

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'relay_invoker') then
    create role relay_invoker nologin;
  end if;
end $$;
grant usage on schema net to relay_invoker;
grant execute on function net.http_post(text, jsonb, jsonb, jsonb, integer) to relay_invoker;

-- web -------------------------------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'web_owner') then create role web_owner nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'web_migrator') then create role web_migrator login noinherit; end if;
  if not exists (select 1 from pg_roles where rolname = 'web_svc') then create role web_svc login; end if;
  execute format('grant web_owner to %I', current_user);
end $$;
alter role web_svc connection limit 3;
alter role web_migrator connection limit 2;
grant web_owner to web_migrator;
create schema if not exists web authorization web_owner;
revoke all on schema web from public, anon, authenticated;
grant usage on schema web to web_svc;
alter default privileges for role web_owner in schema web grant select, insert, update, delete on tables to web_svc;
alter default privileges for role web_owner in schema web grant usage, select on sequences to web_svc;
alter default privileges for role web_owner in schema web grant execute on functions to web_svc;
alter role web_svc set search_path = web;
alter role web_migrator set search_path = web;
alter role web_migrator set role = web_owner;

-- intake ----------------------------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'intake_owner') then create role intake_owner nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'intake_migrator') then create role intake_migrator login noinherit; end if;
  if not exists (select 1 from pg_roles where rolname = 'intake_svc') then create role intake_svc login; end if;
  execute format('grant intake_owner to %I', current_user);
end $$;
alter role intake_svc connection limit 5;
alter role intake_migrator connection limit 2;
grant intake_owner to intake_migrator;
create schema if not exists intake authorization intake_owner;
revoke all on schema intake from public, anon, authenticated;
grant usage on schema intake to intake_svc;
alter default privileges for role intake_owner in schema intake grant select, insert, update, delete on tables to intake_svc;
alter default privileges for role intake_owner in schema intake grant usage, select on sequences to intake_svc;
alter default privileges for role intake_owner in schema intake grant execute on functions to intake_svc;
alter role intake_svc set search_path = intake;
alter role intake_migrator set search_path = intake;
alter role intake_migrator set role = intake_owner;

-- records ---------------------------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'records_owner') then create role records_owner nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'records_migrator') then create role records_migrator login noinherit; end if;
  if not exists (select 1 from pg_roles where rolname = 'records_svc') then create role records_svc login; end if;
  execute format('grant records_owner to %I', current_user);
end $$;
alter role records_svc connection limit 6;
alter role records_migrator connection limit 2;
grant records_owner to records_migrator;
create schema if not exists records authorization records_owner;
revoke all on schema records from public, anon, authenticated;
grant usage on schema records to records_svc;
alter default privileges for role records_owner in schema records grant select, insert, update, delete on tables to records_svc;
alter default privileges for role records_owner in schema records grant usage, select on sequences to records_svc;
alter default privileges for role records_owner in schema records grant execute on functions to records_svc;
alter role records_svc set search_path = records;
alter role records_migrator set search_path = records;
alter role records_migrator set role = records_owner;

-- journeys --------------------------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'journeys_owner') then create role journeys_owner nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'journeys_migrator') then create role journeys_migrator login noinherit; end if;
  if not exists (select 1 from pg_roles where rolname = 'journeys_svc') then create role journeys_svc login; end if;
  execute format('grant journeys_owner to %I', current_user);
end $$;
alter role journeys_svc connection limit 4;
alter role journeys_migrator connection limit 2;
grant journeys_owner to journeys_migrator;
create schema if not exists journeys authorization journeys_owner;
revoke all on schema journeys from public, anon, authenticated;
grant usage on schema journeys to journeys_svc;
alter default privileges for role journeys_owner in schema journeys grant select, insert, update, delete on tables to journeys_svc;
alter default privileges for role journeys_owner in schema journeys grant usage, select on sequences to journeys_svc;
alter default privileges for role journeys_owner in schema journeys grant execute on functions to journeys_svc;
alter role journeys_svc set search_path = journeys;
alter role journeys_migrator set search_path = journeys;
alter role journeys_migrator set role = journeys_owner;

-- crm-engine ------------------------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'crm_engine_owner') then create role crm_engine_owner nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'crm_engine_migrator') then create role crm_engine_migrator login noinherit; end if;
  if not exists (select 1 from pg_roles where rolname = 'crm_engine_svc') then create role crm_engine_svc login; end if;
  execute format('grant crm_engine_owner to %I', current_user);
end $$;
alter role crm_engine_svc connection limit 4;
alter role crm_engine_migrator connection limit 2;
grant crm_engine_owner to crm_engine_migrator;
create schema if not exists crm_engine authorization crm_engine_owner;
revoke all on schema crm_engine from public, anon, authenticated;
grant usage on schema crm_engine to crm_engine_svc;
alter default privileges for role crm_engine_owner in schema crm_engine grant select, insert, update, delete on tables to crm_engine_svc;
alter default privileges for role crm_engine_owner in schema crm_engine grant usage, select on sequences to crm_engine_svc;
alter default privileges for role crm_engine_owner in schema crm_engine grant execute on functions to crm_engine_svc;
alter role crm_engine_svc set search_path = crm_engine;
alter role crm_engine_migrator set search_path = crm_engine;
alter role crm_engine_migrator set role = crm_engine_owner;

-- listings --------------------------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'listings_owner') then create role listings_owner nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'listings_migrator') then create role listings_migrator login noinherit; end if;
  if not exists (select 1 from pg_roles where rolname = 'listings_svc') then create role listings_svc login; end if;
  execute format('grant listings_owner to %I', current_user);
end $$;
alter role listings_svc connection limit 4;
alter role listings_migrator connection limit 2;
grant listings_owner to listings_migrator;
create schema if not exists listings authorization listings_owner;
revoke all on schema listings from public, anon, authenticated;
grant usage on schema listings to listings_svc;
alter default privileges for role listings_owner in schema listings grant select, insert, update, delete on tables to listings_svc;
alter default privileges for role listings_owner in schema listings grant usage, select on sequences to listings_svc;
alter default privileges for role listings_owner in schema listings grant execute on functions to listings_svc;
alter role listings_svc set search_path = listings;
alter role listings_migrator set search_path = listings;
alter role listings_migrator set role = listings_owner;

-- insight ---------------------------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'insight_owner') then create role insight_owner nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'insight_migrator') then create role insight_migrator login noinherit; end if;
  if not exists (select 1 from pg_roles where rolname = 'insight_svc') then create role insight_svc login; end if;
  execute format('grant insight_owner to %I', current_user);
end $$;
alter role insight_svc connection limit 3;
alter role insight_migrator connection limit 2;
grant insight_owner to insight_migrator;
create schema if not exists insight authorization insight_owner;
revoke all on schema insight from public, anon, authenticated;
grant usage on schema insight to insight_svc;
alter default privileges for role insight_owner in schema insight grant select, insert, update, delete on tables to insight_svc;
alter default privileges for role insight_owner in schema insight grant usage, select on sequences to insight_svc;
alter default privileges for role insight_owner in schema insight grant execute on functions to insight_svc;
alter role insight_svc set search_path = insight;
alter role insight_migrator set search_path = insight;
alter role insight_migrator set role = insight_owner;

-- Queues: event queue per consumer + private work queues, each with a DLQ (conventions §5) --------------------
select pgmq.create('q_web') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_web');
select pgmq.create('q_web_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_web_dlq');
select pgmq.create('q_intake') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_intake');
select pgmq.create('q_intake_chunks') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_intake_chunks');
select pgmq.create('q_intake_finalize') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_intake_finalize');
select pgmq.create('q_intake_inspect') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_intake_inspect');
select pgmq.create('q_intake_split') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_intake_split');
select pgmq.create('q_intake_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_intake_dlq');
select pgmq.create('q_intake_chunks_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_intake_chunks_dlq');
select pgmq.create('q_intake_finalize_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_intake_finalize_dlq');
select pgmq.create('q_intake_inspect_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_intake_inspect_dlq');
select pgmq.create('q_intake_split_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_intake_split_dlq');
select pgmq.create('q_records') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_records');
select pgmq.create('q_records_photo_fetch') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_records_photo_fetch');
select pgmq.create('q_records_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_records_dlq');
select pgmq.create('q_records_photo_fetch_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_records_photo_fetch_dlq');
select pgmq.create('q_journeys') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_journeys');
select pgmq.create('q_journeys_work') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_journeys_work');
select pgmq.create('q_journeys_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_journeys_dlq');
select pgmq.create('q_journeys_work_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_journeys_work_dlq');
select pgmq.create('q_crm_engine') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_crm_engine');
select pgmq.create('q_crm_engine_rescore') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_crm_engine_rescore');
select pgmq.create('q_crm_engine_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_crm_engine_dlq');
select pgmq.create('q_crm_engine_rescore_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_crm_engine_rescore_dlq');
select pgmq.create('q_listings') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_listings');
select pgmq.create('q_listings_photos') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_listings_photos');
select pgmq.create('q_listings_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_listings_dlq');
select pgmq.create('q_listings_photos_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_listings_photos_dlq');
select pgmq.create('q_insight') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_insight');
select pgmq.create('q_insight_exports') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_insight_exports');
select pgmq.create('q_insight_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_insight_dlq');
select pgmq.create('q_insight_exports_dlq') where not exists (select 1 from pgmq.list_queues() where queue_name = 'q_insight_exports_dlq');

-- Queue wrappers: the only way service roles touch pgmq (data-hosting §3). ---------------------------------
-- Owned by the bootstrap role (SECURITY DEFINER), executable only by that service's runtime role.

-- web: owns q_web (+ DLQs); sends to q_insight, q_journeys, q_web
create or replace function web.queue_send(p_queue text, p_msg jsonb, p_delay integer default 0) returns bigint
language plpgsql security definer set search_path = '' as $$
declare v_id bigint;
begin
  if not (p_queue = any (array['q_insight', 'q_journeys', 'q_web', 'q_web_dlq']::text[])) then
    raise exception 'queue % is not a queue writable by web', p_queue using errcode = '42501';
  end if;
  select * into v_id from pgmq.send(p_queue, p_msg, p_delay);
  return v_id;
end
$$;
create or replace function web.queue_read(p_queue text, p_vt integer, p_qty integer) returns setof pgmq.message_record
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_web', 'q_web_dlq']::text[])) then
    raise exception 'queue % is not owned by web', p_queue using errcode = '42501';
  end if;
  return query select * from pgmq.read(p_queue, p_vt, p_qty);
end
$$;
create or replace function web.queue_set_vt(p_queue text, p_msg_id bigint, p_vt_offset integer) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_web', 'q_web_dlq']::text[])) then
    raise exception 'queue % is not owned by web', p_queue using errcode = '42501';
  end if;
  perform pgmq.set_vt(p_queue, p_msg_id, p_vt_offset);
end
$$;
create or replace function web.queue_delete(p_queue text, p_msg_id bigint) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_web', 'q_web_dlq']::text[])) then
    raise exception 'queue % is not owned by web', p_queue using errcode = '42501';
  end if;
  return pgmq.delete(p_queue, p_msg_id);
end
$$;
create or replace function web.queue_archive(p_queue text, p_msg_id bigint) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_web', 'q_web_dlq']::text[])) then
    raise exception 'queue % is not owned by web', p_queue using errcode = '42501';
  end if;
  return pgmq.archive(p_queue, p_msg_id);
end
$$;
create or replace function web.queue_depths(out queue_name text, out queue_length bigint, out oldest_msg_age_sec integer) returns setof record
language sql security definer set search_path = '' as $$
  select m.queue_name, m.queue_length, m.oldest_msg_age_sec from pgmq.metrics_all() m where m.queue_name = any (array['q_web', 'q_web_dlq']::text[])
$$;
revoke all on function web.queue_send(text, jsonb, integer) from public, anon, authenticated;
grant execute on function web.queue_send(text, jsonb, integer) to web_svc;
revoke all on function web.queue_read(text, integer, integer) from public, anon, authenticated;
grant execute on function web.queue_read(text, integer, integer) to web_svc;
revoke all on function web.queue_set_vt(text, bigint, integer) from public, anon, authenticated;
grant execute on function web.queue_set_vt(text, bigint, integer) to web_svc;
revoke all on function web.queue_delete(text, bigint) from public, anon, authenticated;
grant execute on function web.queue_delete(text, bigint) to web_svc;
revoke all on function web.queue_archive(text, bigint) from public, anon, authenticated;
grant execute on function web.queue_archive(text, bigint) to web_svc;
revoke all on function web.queue_depths() from public, anon, authenticated;
grant execute on function web.queue_depths() to web_svc;

-- intake: owns q_intake, q_intake_chunks, q_intake_finalize, q_intake_inspect, q_intake_split (+ DLQs); sends to q_insight, q_records, q_web
create or replace function intake.queue_send(p_queue text, p_msg jsonb, p_delay integer default 0) returns bigint
language plpgsql security definer set search_path = '' as $$
declare v_id bigint;
begin
  if not (p_queue = any (array['q_insight', 'q_intake', 'q_intake_chunks', 'q_intake_chunks_dlq', 'q_intake_dlq', 'q_intake_finalize', 'q_intake_finalize_dlq', 'q_intake_inspect', 'q_intake_inspect_dlq', 'q_intake_split', 'q_intake_split_dlq', 'q_records', 'q_web']::text[])) then
    raise exception 'queue % is not a queue writable by intake', p_queue using errcode = '42501';
  end if;
  select * into v_id from pgmq.send(p_queue, p_msg, p_delay);
  return v_id;
end
$$;
create or replace function intake.queue_read(p_queue text, p_vt integer, p_qty integer) returns setof pgmq.message_record
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_intake', 'q_intake_chunks', 'q_intake_finalize', 'q_intake_inspect', 'q_intake_split', 'q_intake_dlq', 'q_intake_chunks_dlq', 'q_intake_finalize_dlq', 'q_intake_inspect_dlq', 'q_intake_split_dlq']::text[])) then
    raise exception 'queue % is not owned by intake', p_queue using errcode = '42501';
  end if;
  return query select * from pgmq.read(p_queue, p_vt, p_qty);
end
$$;
create or replace function intake.queue_set_vt(p_queue text, p_msg_id bigint, p_vt_offset integer) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_intake', 'q_intake_chunks', 'q_intake_finalize', 'q_intake_inspect', 'q_intake_split', 'q_intake_dlq', 'q_intake_chunks_dlq', 'q_intake_finalize_dlq', 'q_intake_inspect_dlq', 'q_intake_split_dlq']::text[])) then
    raise exception 'queue % is not owned by intake', p_queue using errcode = '42501';
  end if;
  perform pgmq.set_vt(p_queue, p_msg_id, p_vt_offset);
end
$$;
create or replace function intake.queue_delete(p_queue text, p_msg_id bigint) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_intake', 'q_intake_chunks', 'q_intake_finalize', 'q_intake_inspect', 'q_intake_split', 'q_intake_dlq', 'q_intake_chunks_dlq', 'q_intake_finalize_dlq', 'q_intake_inspect_dlq', 'q_intake_split_dlq']::text[])) then
    raise exception 'queue % is not owned by intake', p_queue using errcode = '42501';
  end if;
  return pgmq.delete(p_queue, p_msg_id);
end
$$;
create or replace function intake.queue_archive(p_queue text, p_msg_id bigint) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_intake', 'q_intake_chunks', 'q_intake_finalize', 'q_intake_inspect', 'q_intake_split', 'q_intake_dlq', 'q_intake_chunks_dlq', 'q_intake_finalize_dlq', 'q_intake_inspect_dlq', 'q_intake_split_dlq']::text[])) then
    raise exception 'queue % is not owned by intake', p_queue using errcode = '42501';
  end if;
  return pgmq.archive(p_queue, p_msg_id);
end
$$;
create or replace function intake.queue_depths(out queue_name text, out queue_length bigint, out oldest_msg_age_sec integer) returns setof record
language sql security definer set search_path = '' as $$
  select m.queue_name, m.queue_length, m.oldest_msg_age_sec from pgmq.metrics_all() m where m.queue_name = any (array['q_intake', 'q_intake_chunks', 'q_intake_finalize', 'q_intake_inspect', 'q_intake_split', 'q_intake_dlq', 'q_intake_chunks_dlq', 'q_intake_finalize_dlq', 'q_intake_inspect_dlq', 'q_intake_split_dlq']::text[])
$$;
revoke all on function intake.queue_send(text, jsonb, integer) from public, anon, authenticated;
grant execute on function intake.queue_send(text, jsonb, integer) to intake_svc;
revoke all on function intake.queue_read(text, integer, integer) from public, anon, authenticated;
grant execute on function intake.queue_read(text, integer, integer) to intake_svc;
revoke all on function intake.queue_set_vt(text, bigint, integer) from public, anon, authenticated;
grant execute on function intake.queue_set_vt(text, bigint, integer) to intake_svc;
revoke all on function intake.queue_delete(text, bigint) from public, anon, authenticated;
grant execute on function intake.queue_delete(text, bigint) to intake_svc;
revoke all on function intake.queue_archive(text, bigint) from public, anon, authenticated;
grant execute on function intake.queue_archive(text, bigint) to intake_svc;
revoke all on function intake.queue_depths() from public, anon, authenticated;
grant execute on function intake.queue_depths() to intake_svc;

-- records: owns q_records, q_records_photo_fetch (+ DLQs); sends to q_crm_engine, q_insight, q_intake, q_journeys, q_listings, q_web
create or replace function records.queue_send(p_queue text, p_msg jsonb, p_delay integer default 0) returns bigint
language plpgsql security definer set search_path = '' as $$
declare v_id bigint;
begin
  if not (p_queue = any (array['q_crm_engine', 'q_insight', 'q_intake', 'q_journeys', 'q_listings', 'q_records', 'q_records_dlq', 'q_records_photo_fetch', 'q_records_photo_fetch_dlq', 'q_web']::text[])) then
    raise exception 'queue % is not a queue writable by records', p_queue using errcode = '42501';
  end if;
  select * into v_id from pgmq.send(p_queue, p_msg, p_delay);
  return v_id;
end
$$;
create or replace function records.queue_read(p_queue text, p_vt integer, p_qty integer) returns setof pgmq.message_record
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_records', 'q_records_photo_fetch', 'q_records_dlq', 'q_records_photo_fetch_dlq']::text[])) then
    raise exception 'queue % is not owned by records', p_queue using errcode = '42501';
  end if;
  return query select * from pgmq.read(p_queue, p_vt, p_qty);
end
$$;
create or replace function records.queue_set_vt(p_queue text, p_msg_id bigint, p_vt_offset integer) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_records', 'q_records_photo_fetch', 'q_records_dlq', 'q_records_photo_fetch_dlq']::text[])) then
    raise exception 'queue % is not owned by records', p_queue using errcode = '42501';
  end if;
  perform pgmq.set_vt(p_queue, p_msg_id, p_vt_offset);
end
$$;
create or replace function records.queue_delete(p_queue text, p_msg_id bigint) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_records', 'q_records_photo_fetch', 'q_records_dlq', 'q_records_photo_fetch_dlq']::text[])) then
    raise exception 'queue % is not owned by records', p_queue using errcode = '42501';
  end if;
  return pgmq.delete(p_queue, p_msg_id);
end
$$;
create or replace function records.queue_archive(p_queue text, p_msg_id bigint) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_records', 'q_records_photo_fetch', 'q_records_dlq', 'q_records_photo_fetch_dlq']::text[])) then
    raise exception 'queue % is not owned by records', p_queue using errcode = '42501';
  end if;
  return pgmq.archive(p_queue, p_msg_id);
end
$$;
create or replace function records.queue_depths(out queue_name text, out queue_length bigint, out oldest_msg_age_sec integer) returns setof record
language sql security definer set search_path = '' as $$
  select m.queue_name, m.queue_length, m.oldest_msg_age_sec from pgmq.metrics_all() m where m.queue_name = any (array['q_records', 'q_records_photo_fetch', 'q_records_dlq', 'q_records_photo_fetch_dlq']::text[])
$$;
revoke all on function records.queue_send(text, jsonb, integer) from public, anon, authenticated;
grant execute on function records.queue_send(text, jsonb, integer) to records_svc;
revoke all on function records.queue_read(text, integer, integer) from public, anon, authenticated;
grant execute on function records.queue_read(text, integer, integer) to records_svc;
revoke all on function records.queue_set_vt(text, bigint, integer) from public, anon, authenticated;
grant execute on function records.queue_set_vt(text, bigint, integer) to records_svc;
revoke all on function records.queue_delete(text, bigint) from public, anon, authenticated;
grant execute on function records.queue_delete(text, bigint) to records_svc;
revoke all on function records.queue_archive(text, bigint) from public, anon, authenticated;
grant execute on function records.queue_archive(text, bigint) to records_svc;
revoke all on function records.queue_depths() from public, anon, authenticated;
grant execute on function records.queue_depths() to records_svc;

-- journeys: owns q_journeys, q_journeys_work (+ DLQs); sends to q_crm_engine, q_insight, q_listings, q_records, q_web
create or replace function journeys.queue_send(p_queue text, p_msg jsonb, p_delay integer default 0) returns bigint
language plpgsql security definer set search_path = '' as $$
declare v_id bigint;
begin
  if not (p_queue = any (array['q_crm_engine', 'q_insight', 'q_journeys', 'q_journeys_dlq', 'q_journeys_work', 'q_journeys_work_dlq', 'q_listings', 'q_records', 'q_web']::text[])) then
    raise exception 'queue % is not a queue writable by journeys', p_queue using errcode = '42501';
  end if;
  select * into v_id from pgmq.send(p_queue, p_msg, p_delay);
  return v_id;
end
$$;
create or replace function journeys.queue_read(p_queue text, p_vt integer, p_qty integer) returns setof pgmq.message_record
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_journeys', 'q_journeys_work', 'q_journeys_dlq', 'q_journeys_work_dlq']::text[])) then
    raise exception 'queue % is not owned by journeys', p_queue using errcode = '42501';
  end if;
  return query select * from pgmq.read(p_queue, p_vt, p_qty);
end
$$;
create or replace function journeys.queue_set_vt(p_queue text, p_msg_id bigint, p_vt_offset integer) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_journeys', 'q_journeys_work', 'q_journeys_dlq', 'q_journeys_work_dlq']::text[])) then
    raise exception 'queue % is not owned by journeys', p_queue using errcode = '42501';
  end if;
  perform pgmq.set_vt(p_queue, p_msg_id, p_vt_offset);
end
$$;
create or replace function journeys.queue_delete(p_queue text, p_msg_id bigint) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_journeys', 'q_journeys_work', 'q_journeys_dlq', 'q_journeys_work_dlq']::text[])) then
    raise exception 'queue % is not owned by journeys', p_queue using errcode = '42501';
  end if;
  return pgmq.delete(p_queue, p_msg_id);
end
$$;
create or replace function journeys.queue_archive(p_queue text, p_msg_id bigint) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_journeys', 'q_journeys_work', 'q_journeys_dlq', 'q_journeys_work_dlq']::text[])) then
    raise exception 'queue % is not owned by journeys', p_queue using errcode = '42501';
  end if;
  return pgmq.archive(p_queue, p_msg_id);
end
$$;
create or replace function journeys.queue_depths(out queue_name text, out queue_length bigint, out oldest_msg_age_sec integer) returns setof record
language sql security definer set search_path = '' as $$
  select m.queue_name, m.queue_length, m.oldest_msg_age_sec from pgmq.metrics_all() m where m.queue_name = any (array['q_journeys', 'q_journeys_work', 'q_journeys_dlq', 'q_journeys_work_dlq']::text[])
$$;
revoke all on function journeys.queue_send(text, jsonb, integer) from public, anon, authenticated;
grant execute on function journeys.queue_send(text, jsonb, integer) to journeys_svc;
revoke all on function journeys.queue_read(text, integer, integer) from public, anon, authenticated;
grant execute on function journeys.queue_read(text, integer, integer) to journeys_svc;
revoke all on function journeys.queue_set_vt(text, bigint, integer) from public, anon, authenticated;
grant execute on function journeys.queue_set_vt(text, bigint, integer) to journeys_svc;
revoke all on function journeys.queue_delete(text, bigint) from public, anon, authenticated;
grant execute on function journeys.queue_delete(text, bigint) to journeys_svc;
revoke all on function journeys.queue_archive(text, bigint) from public, anon, authenticated;
grant execute on function journeys.queue_archive(text, bigint) to journeys_svc;
revoke all on function journeys.queue_depths() from public, anon, authenticated;
grant execute on function journeys.queue_depths() to journeys_svc;

-- crm-engine: owns q_crm_engine, q_crm_engine_rescore (+ DLQs); sends to q_insight, q_journeys, q_listings, q_web
create or replace function crm_engine.queue_send(p_queue text, p_msg jsonb, p_delay integer default 0) returns bigint
language plpgsql security definer set search_path = '' as $$
declare v_id bigint;
begin
  if not (p_queue = any (array['q_crm_engine', 'q_crm_engine_dlq', 'q_crm_engine_rescore', 'q_crm_engine_rescore_dlq', 'q_insight', 'q_journeys', 'q_listings', 'q_web']::text[])) then
    raise exception 'queue % is not a queue writable by crm-engine', p_queue using errcode = '42501';
  end if;
  select * into v_id from pgmq.send(p_queue, p_msg, p_delay);
  return v_id;
end
$$;
create or replace function crm_engine.queue_read(p_queue text, p_vt integer, p_qty integer) returns setof pgmq.message_record
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_crm_engine', 'q_crm_engine_rescore', 'q_crm_engine_dlq', 'q_crm_engine_rescore_dlq']::text[])) then
    raise exception 'queue % is not owned by crm-engine', p_queue using errcode = '42501';
  end if;
  return query select * from pgmq.read(p_queue, p_vt, p_qty);
end
$$;
create or replace function crm_engine.queue_set_vt(p_queue text, p_msg_id bigint, p_vt_offset integer) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_crm_engine', 'q_crm_engine_rescore', 'q_crm_engine_dlq', 'q_crm_engine_rescore_dlq']::text[])) then
    raise exception 'queue % is not owned by crm-engine', p_queue using errcode = '42501';
  end if;
  perform pgmq.set_vt(p_queue, p_msg_id, p_vt_offset);
end
$$;
create or replace function crm_engine.queue_delete(p_queue text, p_msg_id bigint) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_crm_engine', 'q_crm_engine_rescore', 'q_crm_engine_dlq', 'q_crm_engine_rescore_dlq']::text[])) then
    raise exception 'queue % is not owned by crm-engine', p_queue using errcode = '42501';
  end if;
  return pgmq.delete(p_queue, p_msg_id);
end
$$;
create or replace function crm_engine.queue_archive(p_queue text, p_msg_id bigint) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_crm_engine', 'q_crm_engine_rescore', 'q_crm_engine_dlq', 'q_crm_engine_rescore_dlq']::text[])) then
    raise exception 'queue % is not owned by crm-engine', p_queue using errcode = '42501';
  end if;
  return pgmq.archive(p_queue, p_msg_id);
end
$$;
create or replace function crm_engine.queue_depths(out queue_name text, out queue_length bigint, out oldest_msg_age_sec integer) returns setof record
language sql security definer set search_path = '' as $$
  select m.queue_name, m.queue_length, m.oldest_msg_age_sec from pgmq.metrics_all() m where m.queue_name = any (array['q_crm_engine', 'q_crm_engine_rescore', 'q_crm_engine_dlq', 'q_crm_engine_rescore_dlq']::text[])
$$;
revoke all on function crm_engine.queue_send(text, jsonb, integer) from public, anon, authenticated;
grant execute on function crm_engine.queue_send(text, jsonb, integer) to crm_engine_svc;
revoke all on function crm_engine.queue_read(text, integer, integer) from public, anon, authenticated;
grant execute on function crm_engine.queue_read(text, integer, integer) to crm_engine_svc;
revoke all on function crm_engine.queue_set_vt(text, bigint, integer) from public, anon, authenticated;
grant execute on function crm_engine.queue_set_vt(text, bigint, integer) to crm_engine_svc;
revoke all on function crm_engine.queue_delete(text, bigint) from public, anon, authenticated;
grant execute on function crm_engine.queue_delete(text, bigint) to crm_engine_svc;
revoke all on function crm_engine.queue_archive(text, bigint) from public, anon, authenticated;
grant execute on function crm_engine.queue_archive(text, bigint) to crm_engine_svc;
revoke all on function crm_engine.queue_depths() from public, anon, authenticated;
grant execute on function crm_engine.queue_depths() to crm_engine_svc;

-- listings: owns q_listings, q_listings_photos (+ DLQs); sends to q_insight, q_journeys, q_records, q_web
create or replace function listings.queue_send(p_queue text, p_msg jsonb, p_delay integer default 0) returns bigint
language plpgsql security definer set search_path = '' as $$
declare v_id bigint;
begin
  if not (p_queue = any (array['q_insight', 'q_journeys', 'q_listings', 'q_listings_dlq', 'q_listings_photos', 'q_listings_photos_dlq', 'q_records', 'q_web']::text[])) then
    raise exception 'queue % is not a queue writable by listings', p_queue using errcode = '42501';
  end if;
  select * into v_id from pgmq.send(p_queue, p_msg, p_delay);
  return v_id;
end
$$;
create or replace function listings.queue_read(p_queue text, p_vt integer, p_qty integer) returns setof pgmq.message_record
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_listings', 'q_listings_photos', 'q_listings_dlq', 'q_listings_photos_dlq']::text[])) then
    raise exception 'queue % is not owned by listings', p_queue using errcode = '42501';
  end if;
  return query select * from pgmq.read(p_queue, p_vt, p_qty);
end
$$;
create or replace function listings.queue_set_vt(p_queue text, p_msg_id bigint, p_vt_offset integer) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_listings', 'q_listings_photos', 'q_listings_dlq', 'q_listings_photos_dlq']::text[])) then
    raise exception 'queue % is not owned by listings', p_queue using errcode = '42501';
  end if;
  perform pgmq.set_vt(p_queue, p_msg_id, p_vt_offset);
end
$$;
create or replace function listings.queue_delete(p_queue text, p_msg_id bigint) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_listings', 'q_listings_photos', 'q_listings_dlq', 'q_listings_photos_dlq']::text[])) then
    raise exception 'queue % is not owned by listings', p_queue using errcode = '42501';
  end if;
  return pgmq.delete(p_queue, p_msg_id);
end
$$;
create or replace function listings.queue_archive(p_queue text, p_msg_id bigint) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_listings', 'q_listings_photos', 'q_listings_dlq', 'q_listings_photos_dlq']::text[])) then
    raise exception 'queue % is not owned by listings', p_queue using errcode = '42501';
  end if;
  return pgmq.archive(p_queue, p_msg_id);
end
$$;
create or replace function listings.queue_depths(out queue_name text, out queue_length bigint, out oldest_msg_age_sec integer) returns setof record
language sql security definer set search_path = '' as $$
  select m.queue_name, m.queue_length, m.oldest_msg_age_sec from pgmq.metrics_all() m where m.queue_name = any (array['q_listings', 'q_listings_photos', 'q_listings_dlq', 'q_listings_photos_dlq']::text[])
$$;
revoke all on function listings.queue_send(text, jsonb, integer) from public, anon, authenticated;
grant execute on function listings.queue_send(text, jsonb, integer) to listings_svc;
revoke all on function listings.queue_read(text, integer, integer) from public, anon, authenticated;
grant execute on function listings.queue_read(text, integer, integer) to listings_svc;
revoke all on function listings.queue_set_vt(text, bigint, integer) from public, anon, authenticated;
grant execute on function listings.queue_set_vt(text, bigint, integer) to listings_svc;
revoke all on function listings.queue_delete(text, bigint) from public, anon, authenticated;
grant execute on function listings.queue_delete(text, bigint) to listings_svc;
revoke all on function listings.queue_archive(text, bigint) from public, anon, authenticated;
grant execute on function listings.queue_archive(text, bigint) to listings_svc;
revoke all on function listings.queue_depths() from public, anon, authenticated;
grant execute on function listings.queue_depths() to listings_svc;

-- insight: owns q_insight, q_insight_exports (+ DLQs); sends to q_web
create or replace function insight.queue_send(p_queue text, p_msg jsonb, p_delay integer default 0) returns bigint
language plpgsql security definer set search_path = '' as $$
declare v_id bigint;
begin
  if not (p_queue = any (array['q_insight', 'q_insight_dlq', 'q_insight_exports', 'q_insight_exports_dlq', 'q_web']::text[])) then
    raise exception 'queue % is not a queue writable by insight', p_queue using errcode = '42501';
  end if;
  select * into v_id from pgmq.send(p_queue, p_msg, p_delay);
  return v_id;
end
$$;
create or replace function insight.queue_read(p_queue text, p_vt integer, p_qty integer) returns setof pgmq.message_record
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_insight', 'q_insight_exports', 'q_insight_dlq', 'q_insight_exports_dlq']::text[])) then
    raise exception 'queue % is not owned by insight', p_queue using errcode = '42501';
  end if;
  return query select * from pgmq.read(p_queue, p_vt, p_qty);
end
$$;
create or replace function insight.queue_set_vt(p_queue text, p_msg_id bigint, p_vt_offset integer) returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_insight', 'q_insight_exports', 'q_insight_dlq', 'q_insight_exports_dlq']::text[])) then
    raise exception 'queue % is not owned by insight', p_queue using errcode = '42501';
  end if;
  perform pgmq.set_vt(p_queue, p_msg_id, p_vt_offset);
end
$$;
create or replace function insight.queue_delete(p_queue text, p_msg_id bigint) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_insight', 'q_insight_exports', 'q_insight_dlq', 'q_insight_exports_dlq']::text[])) then
    raise exception 'queue % is not owned by insight', p_queue using errcode = '42501';
  end if;
  return pgmq.delete(p_queue, p_msg_id);
end
$$;
create or replace function insight.queue_archive(p_queue text, p_msg_id bigint) returns boolean
language plpgsql security definer set search_path = '' as $$
begin
  if not (p_queue = any (array['q_insight', 'q_insight_exports', 'q_insight_dlq', 'q_insight_exports_dlq']::text[])) then
    raise exception 'queue % is not owned by insight', p_queue using errcode = '42501';
  end if;
  return pgmq.archive(p_queue, p_msg_id);
end
$$;
create or replace function insight.queue_depths(out queue_name text, out queue_length bigint, out oldest_msg_age_sec integer) returns setof record
language sql security definer set search_path = '' as $$
  select m.queue_name, m.queue_length, m.oldest_msg_age_sec from pgmq.metrics_all() m where m.queue_name = any (array['q_insight', 'q_insight_exports', 'q_insight_dlq', 'q_insight_exports_dlq']::text[])
$$;
revoke all on function insight.queue_send(text, jsonb, integer) from public, anon, authenticated;
grant execute on function insight.queue_send(text, jsonb, integer) to insight_svc;
revoke all on function insight.queue_read(text, integer, integer) from public, anon, authenticated;
grant execute on function insight.queue_read(text, integer, integer) to insight_svc;
revoke all on function insight.queue_set_vt(text, bigint, integer) from public, anon, authenticated;
grant execute on function insight.queue_set_vt(text, bigint, integer) to insight_svc;
revoke all on function insight.queue_delete(text, bigint) from public, anon, authenticated;
grant execute on function insight.queue_delete(text, bigint) to insight_svc;
revoke all on function insight.queue_archive(text, bigint) from public, anon, authenticated;
grant execute on function insight.queue_archive(text, bigint) to insight_svc;
revoke all on function insight.queue_depths() from public, anon, authenticated;
grant execute on function insight.queue_depths() to insight_svc;

