// Generates TypeScript types from the contracts (task F-04):
//  - contracts/generated/ts/<service>.ts  from contracts/openapi/<service>.yaml
//  - contracts/generated/ts/events.ts     from contracts/asyncapi/events.yaml (event `data` payloads + envelope)
// CI regenerates and fails if the committed files differ (contract drift, CLAUDE.md §3.3).
import { readFile, writeFile } from 'node:fs/promises';
import openapiTS, { astToString } from 'openapi-typescript';
import { load as yamlLoad } from 'js-yaml';

const root = new URL('../../', import.meta.url);
const services = ['web', 'intake', 'records', 'journeys', 'crm-engine', 'listings', 'insight'];
const header = '// GENERATED by tools/contracts/gen-types.mjs from contracts/. Do not edit by hand.\n';

for (const s of services) {
  const ast = await openapiTS(new URL(`contracts/openapi/${s}.yaml`, root));
  await writeFile(new URL(`contracts/generated/ts/${s}.ts`, root), header + astToString(ast));
}

// Events: wrap each message's data schema as an OpenAPI component so the same generator can type it.
const events = yamlLoad(await readFile(new URL('contracts/asyncapi/events.yaml', root), 'utf8'));
const schemas = { Envelope: events.components.schemas.Envelope };
const names = [];
for (const [key, msg] of Object.entries(events.components.messages)) {
  const data = msg.payload.allOf[1].properties.data;
  const typeName = key.replace(/(^|_)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
  schemas[typeName] = data;
  names.push([msg.name, typeName]);
}
const doc = { openapi: '3.1.0', info: { title: 'events', version: events.info.version }, paths: {}, components: { schemas } };
const ast = await openapiTS(doc);
const map = names.map(([n, t]) => `  '${n}': components['schemas']['${t}'];`).join('\n');
await writeFile(
  new URL('contracts/generated/ts/events.ts', root),
  header + astToString(ast) +
    `\n/** Event type name → payload \`data\` type. */\nexport interface EventDataMap {\n${map}\n}\nexport type EventType = keyof EventDataMap;\n`,
);
process.stdout.write(`types generated: ${services.length} services + ${names.length} events\n`);
