// Blank rows (the column defaults of the migration): a stub created by an event that arrived before its aggregate's
// creation event, or the starting point of a projection.
import type { DemandRow, OfferRow } from './rows.js';

export function blankOffer(id: string): OfferRow {
  return {
    id,
    code: null,
    property_id: null,
    project_id: null,
    deal_type: null,
    market: null,
    segment: null,
    property_types: [],
    property_type_primary: null,
    bhk_min: null,
    bhk_max: null,
    area_sqft_min: null,
    area_sqft_max: null,
    area_basis: null,
    land_area_sqft: null,
    sale_price_inr_min: null,
    sale_price_inr_max: null,
    rent_monthly_inr_min: null,
    rent_monthly_inr_max: null,
    deposit_inr: null,
    current_rent_inr: null,
    locality: null,
    micromarket: null,
    city: null,
    outside_launch_area: false,
    tenancy_status: null,
    sale_mode: null,
    possession_status: null,
    possession_date: null,
    possession_sort: null,
    furnishing: null,
    unit_count: null,
    source_type: null,
    owner_user_id: null,
    sourced_for_demand_id: null,
    contact_person_ids: [],
    photo_count: 0,
    has_real_photos: false,
    record_stage: null,
    verified_at: null,
    verified_by: null,
    void_reason: null,
    commercial_status: null,
    closed_at: null,
    closing_price_inr: null,
    retired_reason: null,
    life_stage: null,
    life_day: null,
    last_confirmed_at: null,
    confirmed_how: null,
    publication_level: null,
    public_id: null,
    enquiry_count: 0,
    match_suggested_count: 0,
    match_confirmed_count: 0,
    merged_into_id: null,
    created_at_src: null,
  };
}

export function blankDemand(id: string): DemandRow {
  return {
    id,
    code: null,
    deal_types: [],
    deal_type_primary: null,
    market: null,
    segment: null,
    property_types: [],
    property_type_primary: null,
    bhk_min: null,
    bhk_max: null,
    area_sqft_min: null,
    area_sqft_max: null,
    area_basis: null,
    budget_inr_min: null,
    budget_inr_max: null,
    rent_monthly_inr_min: null,
    rent_monthly_inr_max: null,
    micromarkets: [],
    localities: [],
    move_in_by: null,
    stated_tags: {},
    outside_launch_area: false,
    record_stage: null,
    source_type: null,
    owner_user_id: null,
    contact_person_ids: [],
    commercial_status: null,
    sourcing_since: null,
    exit_type: null,
    exit_reason: null,
    revisit_date: null,
    qualified_at: null,
    life_stage: null,
    life_day: null,
    last_confirmed_at: null,
    publication_level: null,
    touch_count: 0,
    match_suggested_count: 0,
    match_confirmed_count: 0,
    last_matching_at: null,
    last_match_count: null,
    void_reason: null,
    merged_into_id: null,
    created_at_src: null,
  };
}
