// Domain fixtures (synthetic values only).
import type { DemandFacts, OfferFacts, ProjectFacts } from '../../src/domain/types.js';

export function offer(over: Partial<OfferFacts> = {}): OfferFacts {
  return {
    id: '00000000-0000-4000-8000-000000000101',
    code: 'INV-00101',
    propertyId: '00000000-0000-4000-8000-000000000201',
    projectId: null,
    dealType: 'Lease',
    market: null,
    segment: 'Residential',
    propertyTypes: ['Apartment'],
    bhkMin: 2,
    bhkMax: 2,
    areaSqftMin: 650,
    areaSqftMax: 650,
    areaBasis: 'Carpet',
    landAreaSqft: null,
    salePriceInrMin: null,
    salePriceInrMax: null,
    rentMonthlyInrMin: 45000,
    rentMonthlyInrMax: 45000,
    locality: 'Andheri West',
    micromarket: 'Andheri',
    city: 'Mumbai',
    outsideLaunchArea: false,
    tenancyStatus: null,
    saleMode: null,
    possessionStatus: null,
    furnishing: 'Semi Furnished',
    possessionDate: null,
    unitCount: null,
    floorBand: 'Mid',
    totalFloors: 20,
    parking: 1,
    amenities: ['Gym', 'Lift'],
    selectedPhotoIds: [],
    voidedReason: null,
    recordStage: 'Verified',
    hasRealPhotos: true,
    commercialStatus: 'Available',
    lifeStage: 'Fresh',
    lifeDay: 3,
    retiredReason: null,
    mergedIntoId: null,
    recordsVersion: 1,
    journeysVersion: 1,
    ...over,
  };
}

export function project(over: Partial<ProjectFacts> = {}): ProjectFacts {
  return {
    id: '00000000-0000-4000-8000-000000000301',
    code: 'PRJ-0031',
    name: 'Skyline Heights',
    developerName: 'Example Developers',
    city: 'Mumbai',
    micromarket: 'Powai',
    locality: 'Powai',
    reraNumber: 'P51800012345',
    possessionDate: '2027-06',
    amenities: ['Pool'],
    offerIds: [],
    recordsVersion: 1,
    ...over,
  };
}

export function demand(over: Partial<DemandFacts> = {}): DemandFacts {
  return {
    id: '00000000-0000-4000-8000-000000000401',
    code: 'DEM-000127',
    dealTypes: ['Lease'],
    market: null,
    segment: 'Commercial',
    propertyTypes: ['Office'],
    micromarkets: ['BKC'],
    areaSqftMin: 1000,
    areaSqftMax: 1500,
    areaBasis: null,
    budgetInrMin: null,
    budgetInrMax: null,
    rentMonthlyInrMin: 180000,
    rentMonthlyInrMax: 260000,
    moveInBy: '2026-12-15',
    status: 'Sourcing',
    lifeStage: 'Fresh',
    exitType: null,
    matched: false,
    postRequested: true,
    sourcingRequestId: null,
    voidedReason: null,
    mergedIntoId: null,
    recordsVersion: 1,
    journeysVersion: 1,
    ...over,
  };
}
